import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import { Toaster } from "react-hot-toast";

const myFont = localFont({
  src: [
    {
      path: "../../public/fonts/RoobertTRIAL-Light.otf",
      weight: "300",
      style: "normal"
    },
    {
      path: "../../public/fonts/RoobertTRIAL-Regular.otf",
      weight: "400",
      style: "normal"
    },
    {
      path: "../../public/fonts/RoobertTRIAL-Medium.otf",
      weight: "500",
      style: "normal"
    },
    {
      path: "../../public/fonts/RoobertTRIAL-SemiBold.otf",
      weight: "600",
      style: "normal"
    },
    {
      path: "../../public/fonts/RoobertTRIAL-Bold.otf",
      weight: "700",
      style: "normal"
    }
  ],
  display: "swap" // for better performance
});

export const metadata: Metadata = {
  title: "Sign Up Page",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={myFont.className}>
        <ReduxProvider>{children}</ReduxProvider>
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
